export const products = [
  {
    id: 1,
    name: "nike 360",
    price: 2500,
    stock: 5,
    description: "Deportivas",
    category: "Deportivas",
    img: "https://res.cloudinary.com/doxkduvdk/image/upload/v1670641662/CoderHouse/remera-nike_qsfpsr.jpg",
  },
  {
    id: 2,
    name: "nike 360",
    price: 2500,
    stock: 5,
    description: "Deportivas",
    category: "Deportivas",
    img: "https://res.cloudinary.com/doxkduvdk/image/upload/v1670641661/CoderHouse/jean_kfzgq4.jpg",
  },
  {
    id: 3,
    name: "nike 360",
    price: 2500,
    stock: 5,
    description: "Deportivas",
    category: "Deportivas",
    img: "https://res.cloudinary.com/doxkduvdk/image/upload/v1670641662/CoderHouse/jean-wrangler_cpqrae.jpg",
  },
  {
    id: 4,
    name: "nike 360",
    price: 2500,
    stock: 5,
    description: "Deportivas",
    category: "Deportivas",
    img: "https://res.cloudinary.com/doxkduvdk/image/upload/v1670641661/CoderHouse/remera-puma_rnspq1.webp",
  },
  {
    id: 5,
    name: "nike 360",
    price: 2500,
    stock: 5,
    description: "Deportivas",
    category: "Deportivas",
    img: "https://res.cloudinary.com/doxkduvdk/image/upload/v1670641661/CoderHouse/crocs_tq3ryr.webp",
  },
  {
    id: 6,
    name: "nike 360",
    price: 2500,
    stock: 5,
    description: "Deportivas",
    category: "Deportivas",
    img: "https://res.cloudinary.com/doxkduvdk/image/upload/v1670641661/CoderHouse/campera-nike_gw6esl.webp",
  },
  {
    id: 7,
    name: "nike 360",
    price: 2500,
    stock: 5,
    description: "Deportivas",
    category: "Deportivas",
    img: "https://res.cloudinary.com/doxkduvdk/image/upload/v1670641661/CoderHouse/campera-puma_saij8p.webp",
  },
  {
    id: 8,
    name: "nike 360",
    price: 2500,
    stock: 5,
    description: "Deportivas",
    category: "Deportivas",
    img: "https://res.cloudinary.com/doxkduvdk/image/upload/v1670641660/CoderHouse/zapatillas_a5mnxj.jpg",
  },
  {
    id: 9,
    name: "nike 360",
    price: 2500,
    stock: 5,
    description: "Deportivas",
    category: "Deportivas",
    img: "https://res.cloudinary.com/doxkduvdk/image/upload/v1670641656/CoderHouse/campera_ahsfc5.jpg",
  },
];
